Rename

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -15,6 +15,7 @@ jobs:
         os:
           - windows-latest
           - ubuntu-latest
+          - macos-latest
         file:
           # - ${{ github.event.repository.name }}
           - bin1
@@ -22,18 +23,38 @@ jobs:
     runs-on: ${{ matrix.os }}
     # outputs:
       # artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
+    env:
+      NAME: ${{ format('target/release/{0}{1}', matrix.file, startsWith(matrix.os, 'windows') && '.exe' || '') }}
+      # Can't access runner context
+      # NEW_NAME: ${{ format('target/release/{0}-{1}-{2}{3}', matrix.file, github.ref_name, matrix.os, startsWith(matrix.os, 'windows') && '.exe' || '') }}
+      ARTIFACT_NAME: Binary-${{ matrix.file }}-${{ matrix.os }}
     steps:
       - uses: actions/checkout@master
       - name: Build
         env:
           CARGO_TERM_COLOR: always
         run: cargo build --release --verbose
+      - name: Naming ${{ env.NEW_NAME }}
+        id: naming
+        shell: bash
+        env:
+          NEW_NAME: >-
+            ${{ format('target/release/{0}-{1}-{2}-{3}{4}',
+              matrix.file, github.ref_name, runner.os, runner.arch, startsWith(matrix.os, 'windows') && '.exe' || '') }}
+        run: |
+          export NAME="$( echo ${{ env.NEW_NAME }} | tr [:upper:] [:lower:] )"
+          echo "FILENAME=$NAME" >> $GITHUB_OUTPUT
+      - name: Rename files
+        shell: bash
+        run: |
+          mv $NAME ${{ steps.naming.outputs.FILENAME }}
       - name: Upload
         uses: actions/upload-artifact@master
         id: artifact-upload-step
         with:
-          name: Binary-${{ matrix.file }}-${{ matrix.os }}
-          path: target/release/${{ matrix.file }}${{ runner.os == 'Windows' && '.exe' || '' }}
+          name: ${{ env.ARTIFACT_NAME }}
+          # path: ${{ env.NEW_NAME }}
+          path: ${{ steps.naming.outputs.FILENAME }}
       # - name: Output artifact URL
       #   run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
 
@@ -45,18 +66,22 @@ jobs:
         os:
           - windows-latest
           - ubuntu-latest
+          - macos-latest
         file:
           # - ${{ github.event.repository.name }}
           - bin1
           - bin2
     runs-on: ubuntu-latest
     needs: build
+    if: '!cancelled()' # always(), Same as success() || failure()
     permissions:
       contents: write
+    env:
+      ARTIFACT_NAME: Binary-${{ matrix.file }}-${{ matrix.os }}
     steps:
       - uses: actions/download-artifact@master
         with:
-          name: Binary-${{ matrix.file }}-${{ matrix.os }}
+          name: ${{ env.ARTIFACT_NAME }}
       - name: List files
         run: |
           ls -lih
@@ -68,4 +93,5 @@ jobs:
           files: '*'
       - name: Done
         run: |
-          echo "### [${{ github.ref_name }}](https://github.com/$GITHUB_REPOSITORY/releases/tag/${{ github.ref_name }}) Released! :rocket:" >> $GITHUB_STEP_SUMMARY
+          echo "### [${{ github.ref_name }}](https://github.com/$GITHUB_REPOSITORY/releases/tag/${{ github.ref_name }}) Released! :rocket:" \
+            >> $GITHUB_STEP_SUMMARY
